version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "m2en"
    target-branch: main
    commit-message:
      prefix: chore
    labels:
      - "🔮dependabot: update"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "m2en"
    target-branch: main
    commit-message:
      prefix: chore
    labels:
      - "🔮dependabot: update(gh-actions)"
