name: eslint

on:
  push:
    branches:
      - master
    paths:
      - "src/**/**/*.ts"
      - "src/**/**/*.tsx"
  pull_request:
    paths:
      - "src/**/**/*.ts"
      - "src/**/**/*.tsx"

jobs:
  lint:
    name: eslint(next)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install packages
        run: yarn
      - name: prettier
        run: yarn lint